### ISSUE TITLE
Include `channel_width_mapped` outputs in analysis to generate channel width prediction equation

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#150]
Thanks to @smnorris and [channel_width_mapped.sql](https://github.com/NewGraphEnvironment/bcfishpass/blob/main/01_prep/habitat/02_channel_width/sql/channel_width_mapped.sql) we now have tens of thousands more channel width measurements for double line stream segments than we did for our last run through the [Bayesian analysis](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/blob/master/docs/channel-width-21.pdf) from @joethorley.  

I can incorporate these measurements into [channel_width_analyze.sql](https://github.com/NewGraphEnvironment/bcfishpass/blob/newgraph/01_prep/04_channel_width/sql/channel_width_measured_analyze.sql) so they are prepped to run through a fresh analysis to feed [channel_width_modelled.sql](https://github.com/NewGraphEnvironment/bcfishpass/blob/main/01_prep/habitat/02_channel_width/sql/channel_width_modelled.sql).  

During this process, I can do a bit of QA on [fiss_stream_sample_sites_events.sql](https://github.com/NewGraphEnvironment/bcfishpass/blob/main/01_prep/habitat/02_channel_width/sql/fiss_stream_sample_sites_events.sql) and [channel_width_mapped.sql](https://github.com/NewGraphEnvironment/bcfishpass/blob/main/01_prep/habitat/02_channel_width/sql/channel_width_mapped.sql)

**Comment by NewGraphEnvironment** [comment]
I ran through 10 stream segments in the BULK that have outputs from `channel_width_mapped`. QA notes are here so when we close the issue we can find this.   

`channel_width_mapped` is absolute velvet and so far appears to do a perfect job of both tying `whse_basemapping.fwa_stream_networks_sp` to `whse_basemapping.fwa_linear_boundaries_sp` and getting the average of multiple amalgamated widths using the two layers.  Amazing.

8 out of the ten segments I looked at appeared to have `channel_width_mapped` column outputs very similar to how things appeared on aerial imagery (google and bing).  Maybe not surprisingly, limitations of the measurements seem to be related to the construction of the `whse_basemapping.fwa_linear_boundaries_sp` layer.  An example of a discrepancy between the GIS layer and aerial imagery that can result from this is:

`whse_basemapping.fwa_stream_networks_sp` = 17024663
`channel_width_mapped` column output is 31.36m but looking at aerial imagery it looks like it is closer to 10m... A pretty big diff.

`whse_basemapping.fwa_stream_networks_sp` = 17078400
Interestingly - this feature is only 6 m long.... The output width isn't bad but it might have been more accurate if the segment were much longer. Wondering if there is value in putting a minimum length on which features can be selected.  Might not matter.  Not sure. If we were made of time we could see how often features are under a certain length in `bcfishpass.channel_width_mapped` and QA a bunch of them...

**Comment by smnorris** [comment]
feature 17024663 is only 0.8m long! But much of the stream along there does seem to be narrower than mapped in FWA.

Beyond mapping inconsistencies, I think the biggest potential for error in the measurement of the mapped width is where there are islands in the middle of the channel. The script looks for the closest opposite bank and I did not see an easy way in the attributes to ensure that the opposite bank is not part of an island.  There is probably a way to filter the features to make sure the bank is not an island but it is mostly a minor thing so I didn't pursue it too far.

**Comment by joethorley** [comment]
Whether the island has vegetation is often selected as a key distinction for whether the river is in two channels as opposed to two braids.

**Comment by NewGraphEnvironment** [comment]
From the limited review that I did, it didn't see any instances of where islands were digitized into [whse_basemapping.fwa_linear_boundaries_sp](https://catalogue.data.gov.bc.ca/dataset/freshwater-atlas-linear-boundaries) even though they were present in near half of the stream segments I looked at.  Often they only comprised a small part of the segment too though.

**Comment by smnorris** [comment]
Ok, I dug a bit more and refreshed my memory. It is just a minor edge case, not a big potential for error. The script only considers the primary flow line of the channel (`edge_type` = 1250), so we don't have to worry about defining channels, the FWA does that for us. 

The script starts at the stream flow line and looks for the closest right bank (`edge_type`s 1800, 1825, 1900) and the closest left bank (`edge_type`s 1850, 1875, 1950).  This finds the correct banks almost all the time... but for a very wide channel, one of the closest left/right bank features to the flow line may actually be on the opposite side of a narrow island. To fix the issue, I think the query would have to ensure that it uses only one island bank to make the measurement, not two. But this is likely not worth fixing because it is very rare, and the difference to the correct width value is small relative to the large width where it may occur.

**Comment by smnorris** [comment]
Here's an illustration near the mouth of the Nass. Measuring width for linear_feature_id 111072388 near point A, the closest right bank is point B rather than where we want it at point C.
![Screen Shot 2021-06-17 at 5 18 56 PM](https://user-images.githubusercontent.com/1323293/122487804-f0601100-cf90-11eb-9ec8-168fb6e9962f.png)

**Comment by smnorris** [comment]
Updating this:
- revert channel width calculation back to previous method using % intervals rather than set distance
- use 30 samples along each line segment
- just calculate average width for a segment rather than outputting a table of points, but add a column holding standard deviation of the calculated widths

**Comment by NewGraphEnvironment** [comment]
Seems like `cw_stddev` and `channel_width` have maybe been switched somehow. I can't see why in the [code ](https://github.com/smnorris/bcfishpass/blob/main/01_prep/habitat/02_channel_width/sql/channel_width_mapped.sql) though.


 I looked at a few of the mapped segments in the BULK and the `cw_stddev ` is closer to what I would estimate the `channel_width` at.  Additionally, `cw_stddev ` is always way bigger that the `channel_width`...
