### ISSUE TITLE
modelled_crossing_type_source - check repeated codes, consider adding to crossings table, consider adding a manual review code

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#23]
Not sure why ali.crossings `modelled_crossing_id`  `4606812`  is listed as `PASSABLE`  .  Was this reviewed by hand or are there bridge details from a railway layer? If so, should there be a flag to indicate this?

I had a look at https://github.com/smnorris/bcfishpass/blob/main/01_prep/01_modelled_stream_crossings/sql/08_identify_open_bottom_structures.sql for clues but couldn't figure things out.

**Comment by smnorris** [comment]
In `bcfishpass.modelled_stream_crossings` see column `modelled_crossing_type_source`.
For `4606812` (about 7km south of Fernie on the CP line) it is `GBA_RAILWAY_STRUCTURE_LINES_SP, GBA_RAILWAY_STRUCTURE_LINES_SP, GBA_RAILWAY_STRUCTURE_LINES_SP`.

This is the data source for that crossing: https://catalogue.data.gov.bc.ca/dataset/railway-structure-line

This is where it gets applied, only bridges are taken from that layer: https://github.com/smnorris/bcfishpass/blob/89d1cd18520d6227dfae9bcf955ac4b41091ef0a/01_prep/01_modelled_stream_crossings/sql/08_identify_open_bottom_structures.sql#L62

Manually reviewed modelled crossings status changes are all here: https://github.com/smnorris/bcfishpass/blob/main/01_prep/01_modelled_stream_crossings/data/modelled_stream_crossings_fixes.csv

Based on this review I think a few things could be improved:
-`modelled_crossing_type_source` could be updated when applying the fixes, with `MANUAL REVIEW` or similar added
- I'm not sure why the value ``GBA_RAILWAY_STRUCTURE_LINES_SP` is repeated 3x in the current data. Probably because the script got run three times but that should be checked
- more info from `modelled_stream_crossings` table could be pulled through into the unified `crossings` table so it is easier to work with
